### ISSUE TITLE
Search error: this.props.getWorkflowStatus is not a function

### ISSUE THREAD

**Issue by martinjagodic** [decaporg/decap-cms#7550]
**Describe the bug**
When searchin on pages with EW disabled, CMS throws error:
```
TypeError: this.props.getWorkflowStatus is not a function
    at EntryListing.js:119:41
```

**Applicable Versions:**
3.8.0

Introduced with https://github.com/decaporg/decap-cms/pull/7495
